apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: pyforge-python-school-3-celery_worker:latest
        command: ["celery", "-A", "src.celery_worker", "worker", "--loglevel=info"]
        env:
          - name: REDIS_URL
            value: "redis://redis:6379"
        volumeMounts:
          - name: app-volume
            mountPath: /app
      volumes:
        - name: app-volume
          hostPath:
            path: /path/to/your/local/app
            type: Directory
