name: ci

on:
  push:
    branches:
      - ci_hw  # Replace with your branch name
  pull_request:
    branches:
      - ci_hw  # Replace with your branch name
jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install flake8

    - name: Run flake8
      run: flake8 .

    - name: Run tests
      run: pytest src/test_script.py
